#!/usr/bin/env bash

# Relative regression limits (noise-aware).
MAX_DROP_VIEWS_PER_SEC_PCT=0.15
MAX_DROP_FINALIZED_TPS_PCT=0.15
MAX_DROP_INCLUSION_RATE_PCT=0.10
MAX_INCREASE_LATENCY_P95_PCT=0.20
MAX_INCREASE_LATENCY_P99_PCT=0.25

# Absolute degradation guardrails to avoid tiny/noisy delta failures.
MAX_DROP_VIEWS_PER_SEC_ABS=0.15
MAX_DROP_FINALIZED_TPS_ABS=0.80
MAX_DROP_INCLUSION_RATE_ABS=0.05
MAX_INCREASE_LATENCY_P95_ABS_MS=500
MAX_INCREASE_LATENCY_P99_ABS_MS=800

# Hard floors/caps (independent from baseline) for shared runners.
ABS_MIN_VIEWS_PER_SEC=10.00
ABS_MIN_FINALIZED_TPS=4.00
ABS_MIN_INCLUSION_RATE=0.80
ABS_MAX_LATENCY_P95_MS=6000
ABS_MAX_LATENCY_P99_MS=9000
